version: '3.8'

services:
  app:
    image: node:20
    container_name: papermill-frontend-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5174:5174"
    command: sh -c "npm install && npm run dev"
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1