services:
  app:
    image: node:20
    container_name: papermill-frontend-app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules  # Evita conflictos con node_modules del host
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1
      - CHOKIDAR_USEPOLLING=true  # Importante para Docker en algunos sistemas